homework 4
mishadawg/react_app_geek pull request #4
Opened 2021-01-28 10:15 UTC by mishadawg

console errors

2021-01-28 10:35 UTC, mishadawg commented
ошибки которые вы заметили в предыдущем пул реквесте вроде убрал.
тут консоль ошибки не рендерят приложение.

2021-01-31 09:22 UTC, SokolAlexander commented on static_src/components/ChatList.jsx
> +                <Link to="/chat/1/">
у вас здесь статический список ссылок, со списком чатов не связан ( то есть если изменятся данные о количестве чатов - здесь ничего не изменится). Рекомендую вынести список чатов в стейт компонента повыше и здесь рендерить мапом

2021-01-31 09:23 UTC, SokolAlexander commented on static_src/components/MessageField.jsx
> +                        onKeyUp={ (event) => this.handleKeyUp }
опять стрелки в рендере)

2021-01-31 09:23 UTC, SokolAlexander commented on static_src/components/Router.jsx
> +               <Route exact={ true } path='/' component={ Layout } />
можно просто exact вместо exact={true}

2021-01-31 09:24 UTC, SokolAlexander commented on static_src/components/Router.jsx
> +               />
а профиль?

2021-01-31 09:24 UTC, SokolAlexander requested changes
в целом все ок, оставил пару замечаний, рекомендую поправить)

2021-02-08 08:04 UTC, SokolAlexander commented on static_src/components/ChatList.jsx
> +                <Link to="/chat/2/">
2?
рендерьте мапом по массиву чатов

2021-02-08 08:04 UTC, SokolAlexander commented on static_src/components/MessageField.jsx
> +           1: {title: 'Чат 1', messageList: [1]},
зачем это здесь если у вас есть редакс

2021-02-08 08:05 UTC, SokolAlexander approved these changes
Перенесите все данные в редакс

2021-02-10 12:59 UTC, merged